[target.riscv32imac-unknown-none-elf]
# runner = "espflash flash --monitor -L defmt"
runner = "probe-rs run --chip=esp32c6"

[env]
DEFMT_LOG = "info,garage_sensor=trace,mcutie=debug"
ESP_LOG = "trace"
ESP_WIFI_CSI_ENABLE = "true"

[build]
rustflags = [
  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  "-C",
  "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
